### List

In [3]:
# List Method
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [ ]:
# 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort'

# 1. append

# - It takes a value argument.
# - It appends (add at the end) the element to the list.
# - It makes the changes in the existing list.
# - It does not returns anything

l = [1,2,3,4,5,6,7]
a = l.append(8)  # It will add only one element, where adding two or more element will throws error
print(l)

l = [1,2,3,4,5,6,7]
a = l.append({4:'sam'})
print(l)

b = (5,3,7)

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, {4: 'sam'}]


In [13]:
# extend()

# - It takes an iterable as argument.
# - It appends the elements of the iterable to the list one by one.

# lst.extend(iterable)

l = [1,2,3,4,5,6,7]
a = 'Python'
x = (10,20,30,40,50,60)

e = l.extend(a)
print(l)

d = l.extend(x)
print(l)

[1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n']
[1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 10, 20, 30, 40, 50, 60]


In [23]:
# index()

# - It retruns the index of the first occurence of the element from left to right.
# lst.index(element)

l = [1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 1, 2, 3, 4, 5, 6, 7]

print(l.index('P')) # - to find the index of the elements.
print(l.index(2,0))
print(l.index(3,3))

14
1
9


In [27]:
# count()

# - It returns the number of occurences of an element.

l = [1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 1, 2, 3, 4, 5, 6, 7]
print(l.count(2))
print(l.count(100))

3
0


In [35]:
# insert()

# - It inserts an element at the specific index in a list.
# - The exisitng element at that index shifts to the right side.

# l.insert(index,element)

l = [1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 1, 2, 3, 4, 5, 6, 7]
l.insert(2,200)
print(l)
l.insert(-1,100000000)
print(l)
l.insert(len(l),999999999)
print(l)
l.insert(-(len(l)+1),1010110)
print(l)

[1, 2, 200, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 1, 2, 3, 4, 5, 6, 7]
[1, 2, 200, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 1, 2, 3, 4, 5, 6, 100000000, 7]
[1, 2, 200, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 1, 2, 3, 4, 5, 6, 100000000, 7, 999999999]
[1010110, 1, 2, 200, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 1, 2, 3, 4, 5, 6, 100000000, 7, 999999999]


In [67]:
# pop()
# - It takes an index as an argument.
# - It returns the element availabel at that index and removes it from the list.
# - By default it returns and removes the last element.
# - For any invalid index it raises IndexError.

l = [True, "Python", 55 , 65.4, (6+8j), None, (1,2,3,4), {1:100, 2:200}]
print(l)
print()
print(l.pop(4),l)
print()
print(l.pop(6),l)


[True, 'Python', 55, 65.4, (6+8j), None, (1, 2, 3, 4), {1: 100, 2: 200}]

(6+8j) [True, 'Python', 55, 65.4, None, (1, 2, 3, 4), {1: 100, 2: 200}]

{1: 100, 2: 200} [True, 'Python', 55, 65.4, None, (1, 2, 3, 4)]


In [59]:
a = ['emp_1','Prasanth', 30,'Salem', 636014]
b = ['emp_2','Prathap', 32, 'Bangalore', 540061]

key = a.pop(0)
key2 = b.pop(0)
d = {key:a}
c = {key2:b}
print(d,c)

{'emp_1': ['Prasanth', 30, 'Salem', 636014]} {'emp_2': ['Prathap', 32, 'Bangalore', 540061]}


In [64]:
# remove()
# - It takes a value as argument.
# - It removes the first occurence of the value from the list.
# - If the value is not found then it raises ValueError.

l = [1, 2, 200, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 1, 2, 3, 4, 5, 6, 7]
print(f'{l.remove(5)} {l} ')

None [1, 2, 200, 3, 4, 6, 7, 1, 2, 3, 4, 5, 6, 7, 'P', 'y', 't', 'h', 'o', 'n', 1, 2, 3, 4, 5, 6, 7] 


In [74]:
name = ['sam','prasanth',None,'Raj','Praveen',None,None,'Shive',None,'Kumar']
print(name)
for i in name:
    if None in name:
        name.remove(None)
        print(name)
l = list(name)
print(l,type(l))

['sam', 'prasanth', None, 'Raj', 'Praveen', None, None, 'Shive', None, 'Kumar']
['sam', 'prasanth', 'Raj', 'Praveen', None, None, 'Shive', None, 'Kumar']
['sam', 'prasanth', 'Raj', 'Praveen', None, 'Shive', None, 'Kumar']
['sam', 'prasanth', 'Raj', 'Praveen', 'Shive', None, 'Kumar']
['sam', 'prasanth', 'Raj', 'Praveen', 'Shive', 'Kumar']
['sam', 'prasanth', 'Raj', 'Praveen', 'Shive', 'Kumar'] <class 'list'>


In [79]:
# reverse()
# - It reverses a list.
# - It makes the changes in the existing list.
# - It does not return a new object.

a = [True, "Python", 55 , 65.4, (6+8j), None, (1,2,3,4), {1:100, 2:200}]
b = a.reverse()
print(a)
print(a.reverse(),a)

[{1: 100, 2: 200}, (1, 2, 3, 4), None, (6+8j), 65.4, 55, 'Python', True]
None [True, 'Python', 55, 65.4, (6+8j), None, (1, 2, 3, 4), {1: 100, 2: 200}]


In [109]:
# sort()
# - It sorts a list in ascending order.
# - It makes the changes in the existing list.
# - It does not return a new object.
# - Note: The elements of the list must be compatible to comparison operator.

# int/float <-> int/float
# str <-> str

l = [1, 2, 200, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]

print(l.sort(),l)
print()
print(l.sort(reverse=True),l)
print()

a = list ('akdjfoejranroie')
print(a.sort(),a)
print()
print(a.sort(reverse=True),a)


None [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 200]

None [200, 7, 7, 7, 6, 6, 6, 5, 5, 5, 4, 4, 4, 3, 3, 3, 2, 2, 2, 1, 1, 1]

None ['a', 'a', 'd', 'e', 'e', 'f', 'i', 'j', 'j', 'k', 'n', 'o', 'o', 'r', 'r']

None ['r', 'r', 'o', 'o', 'n', 'k', 'j', 'j', 'i', 'f', 'e', 'e', 'd', 'a', 'a']


In [123]:
# copy()

# - It copies the elements of an existing list and returns a new list.

a = [1, 2, 3, 4, 5, 3, 4, 5, 6, 7]
b = a
print(a)
print(b)
a[0] = 100
print(a)
print(b)
a[-1] = 88
print(a)
print(b)
print()

x = [1, 2, 3, 4, 5, 3, 4, 5, 6, 7]
y = x.copy()
print(id(x))
print(id(y))

x[0] = 129
print(x)
print(y)
y[-1] = 909
print(x)
print(y)
print()
print(x is y)

[1, 2, 3, 4, 5, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 3, 4, 5, 6, 7]
[100, 2, 3, 4, 5, 3, 4, 5, 6, 7]
[100, 2, 3, 4, 5, 3, 4, 5, 6, 7]
[100, 2, 3, 4, 5, 3, 4, 5, 6, 88]
[100, 2, 3, 4, 5, 3, 4, 5, 6, 88]

2686958010176
2686958005504
[129, 2, 3, 4, 5, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 3, 4, 5, 6, 7]
[129, 2, 3, 4, 5, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 3, 4, 5, 6, 909]

False


In [125]:
# clear()
# - It removes all the elements from a list and makes it empty.

(x.clear())
print(x)

[]


In [ ]:
# Mutability of list
# - A list is a mutable objects.
# - We can modify the elements after defining a list.
# - The memory address remains the before and after the modification.

l = [20,30,40,50]
print(l,id(l))

l[0] = True # if we not getting any error on this, then item assignment is possible. -- which means it is mutable
print(l,id(l))

[20, 30, 40, 50] 2686958150464
[True, 30, 40, 50] 2686958150464


In [130]:
# Nested list also known as 2D lsit

# - When we have a list within another list, we get a nested list, 
# - 2D list ---> [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]] : 5 inner list. each inner list has 3 elements
# - The number of inner list represent the number of rows in table or matrix
# - The number of elements each inner list contains represents the number of coloumn in table or matrix

a = [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]

import numpy as np
import pandas as pd


print(np.array(a))
print()
print(pd.DataFrame(a))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15


In [134]:
# Indexing of a 2-D list

l = [10,20,30,40,[100,200,300],32,43,23,56]

print(l[4][0]) # to get 100
print(l[4][-1]) # to get 300

100
300


In [163]:
# Creating a 2-D list

# - create 3*4 list of numbers
# - outer loop always gives the number of rows and inner loop always gives the number of coloumns

o = []
i = []
for a in range(1,4): # ---> gives rows
    for b in range(1,5): # ---> gives coloumns
        i.append(a*b)
    print(i)
    o.append(i)
    print(o)
    print('----------------')
    i = []
print(o)
print()

import numpy as np
print(np.array(o))
print()

import pandas as pd
print(pd.DataFrame(o))
print()

[1, 2, 3, 4]
[[1, 2, 3, 4]]
----------------
[2, 4, 6, 8]
[[1, 2, 3, 4], [2, 4, 6, 8]]
----------------
[3, 6, 9, 12]
[[1, 2, 3, 4], [2, 4, 6, 8], [3, 6, 9, 12]]
----------------
[[1, 2, 3, 4], [2, 4, 6, 8], [3, 6, 9, 12]]

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]

   0  1  2   3
0  1  2  3   4
1  2  4  6   8
2  3  6  9  12



In [172]:
c = [5 for i in range(4)]
print(c)
print()

a = [c for i in range(3)]
print(a)
print()

com = [[i*j for i in range (1,5)] for j in range (1,4)]
print(com)
print()

import numpy as np
print(np.array(com))
print()

import pandas as pd
print(pd.DataFrame(com))

[5, 5, 5, 5]

[[5, 5, 5, 5], [5, 5, 5, 5], [5, 5, 5, 5]]

[[1, 2, 3, 4], [2, 4, 6, 8], [3, 6, 9, 12]]

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]

   0  1  2   3
0  1  2  3   4
1  2  4  6   8
2  3  6  9  12


In [176]:
c = [[eval(input('Enter a value : ')) for i in range (3)] for j in range (3)]
print(c)
print()

import numpy as np
print(np.array(c))
print()

import pandas as pd
print(pd.DataFrame(c))

[[123, 45, 'sam'], [8.99, 'Prasanth', 34], [1.0, 5.4, 'Ravi']]

[['123' '45' 'sam']
 ['8.99' 'Prasanth' '34']
 ['1.0' '5.4' 'Ravi']]

        0         1     2
0  123.00        45   sam
1    8.99  Prasanth    34
2    1.00       5.4  Ravi


In [219]:
a = []
b = []

for i in range(1,4):
    for j in range(11,14):
        a.append(j)     
    b.append(a)
    print(a)
    a = []
print()
print(b)

print()    

import pandas as pd
import numpy as np

print(pd.DataFrame(b))
print()
print(np.array(b))


[11, 12, 13]
[11, 12, 13]
[11, 12, 13]

[[11, 12, 13], [11, 12, 13], [11, 12, 13]]

    0   1   2
0  11  12  13
1  11  12  13
2  11  12  13

[[11 12 13]
 [11 12 13]
 [11 12 13]]
